--- ส่วนของ Blacklist ปืน  ---
weaponblacklist = {	
	
	--[["WEAPON_STICKYBOMB",
	"WEAPON_RAILGUN",
	"WEAPON_HOMINGLAUNCER",	
	"WEAPON_MARKSMANRIFLE",
	"WEAPON_GRENADELAUNCHER",
	"WEAPON_GRENADE",
	"WEAPON_KNIFE",
	--"WEAPON_NIGHTSTICK",
	"WEAPON_HAMMER",
	"WEAPON_BAT",
	"WEAPON_CROWBAR",
	--"WEAPON_GOLFCLUB",
	"WEAPON_BOTTLE",
	"WEAPON_DAGGER",
	"WEAPON_HATCHET",
	"WEAPON_MACHETE",
	"WEAPON_FLASHLIGHT",
	"WEAPON_SWITCHBLADE",
	"WEAPON_POOLCUE",
	"WEAPON_WRENCH",
	"WEAPON_BATTLEAXE",	

-------  TYPE ปืนพก  -------

	--"WEAPON_PISTOL",
	"WEAPON_PISTOLMK2",
	"WEAPON_COMBATPISTOL",
--	"WEAPON_PISTOL50",
	"WEAPON_SNSPISTOL",
	"WEAPON_HEAVYPISTOL",
	"WEAPON_VINTAGEPISTOL",
	"WEAPON_MARKSMANPISTOL",
	"WEAPON_REVOLVER",
	"WEAPON_APPISTOL",
	--"WEAPON_STUNGUN",
	"WEAPON_FLAREGUN",

------ MACHINE GUNS ------

	"WEAPON_MICROSMG",
	"WEAPON_MACHINEPISTOL",
	"WEAPON_SMG",
	"WEAPON_SMGMK2",
	"WEAPON_ASSAULTSMG",
	"WEAPON_COMBATPDW",
	"WEAPON_MG",
	"WEAPON_COMBATMG",
	"WEAPON_COMBATMG2",
	"WEAPON_MGMK2",
	"WEAPON_GUSENBERG",
	"WEAPON_MINISMG",


	------- ASSAULT RIFLES -----

	"WEAPON_ASSAULTRIFLE",
	"WEAPON_ASSAULTRIFLEMK2",
	"WEAPON_CARBINERIFLE",
	"WEAPON_CARBINERIFLEMK2",
	"WEAPON_ADVANCEDRIFLE",
	"WEAPON_SPECIALCARBINE",
	"WEAPON_BULLPUPRIFLE",
	"WEAPON_COMPACTRIFLE",


	----- SNIPER RIFLE ------

	"WEAPON_SNIPERRIFLE",
--	"WEAPON_HEAVYSNIPER",
	"WEAPON_HEAVYSNIPERMK2",
	"WEAPON_MARKSMANRIFLE",

	----- SHOTGUN --------

	"WEAPON_PUMPSHOTGUN",
	"WEAPON_SAWNOFFSHOTGUN",
	"WEAPON_BULLPUPSHOTGUN",
	"WEAPON_ASSAULTSHOTGUN",
	"WEAPON_MUSKET",
	"WEAPON_HEAVYSHOTGUN",
	"WEAPON_DUBBLEBARRELSHOTGUN",
	"WEAPON_AUTOSHOTGUN",
	"WEAPON_DBSHOTGUN",

	----- HEAVY WEAPONS -----

	"WEAPON_GRENADELAUNCHER",
	"WEAPON_RPG",
	"WEAPON_MINIGUN",
	"WEAPON_FIREWORK",
	"WEAPON_RAILGUN",
	"WEAPON_HOMMINGLAUNCHER",
	"WEAPON_GRENADELAUNCHERSMOKE",
	"WEAPON_COMPACTLAUNCHER",

	----- THROWN WEAPONS ------

	"WEAPON_GRENADE",
	"WEAPON_STICKYBOMP",
	"WEAPON_PROXIMITYMINE",
	--"WEAPON_BZGAS",
	"WEAPON_MOLOTOV",
	"WEAPON_FIREEXTINGUISHER",
	--"WEAPON_PETROLCAN",
	"WEAPON_FLARE",
--	"WEAPON_SNOWBALL",
	--"WEAPON_SMOKEGRENADE",
	"WEAPON_PIPEBOMB",
	"WEAPON_PROXMINE",
	"WEAPON_HOMINGLAUNCHER",
	"WEAPON_STINGER",
	"WEAPON_PISTOL_MK2",
	"WEAPON_COMBATMG_MK2",
	"­WEAPON_ASSAULTRIFLE_MK2",
	"­WEAPON_ASLTRIFLE",
	"WEAPON_SMG_MK2",
	"­WEAPON_­HEAVYSNIPER_MK2",
	"WEAPON_CARBINERIFLE_MK2",
	"WEAPON_ASSAULTRIFLE_MK2"]]--	

}


---- ส่วนของ Weapon BlackList ----

Citizen.CreateThread(function()
	while true do
		Citizen.Wait(7)

		playerPed = GetPlayerPed(-1)
		if playerPed then
			nothing, weapon = GetCurrentPedWeapon(playerPed, true)

			if disableallweapons then
				RemoveAllPedWeapons(playerPed, true)
			else
				if isWeaponBlacklisted(weapon) then

					RemoveAllPedWeapons(playerPed,false)
					--RemoveWeaponFromPed(playerPed, weapon)
					sendForbiddenMessage("This weapon is blacklisted!")
				end
			end
		end
	end
end)

function isWeaponBlacklisted(model)
	for _, blacklistedWeapon in pairs(weaponblacklist) do
		if model == GetHashKey(blacklistedWeapon) then
			return true
		end
	end

	return false
end